---
abstract: 'Add virtual columns to DBIx::Class schemata'
author:
  - 'Maroš Kollár'
build_requires:
  DBD::SQLite: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-VirtualColumns
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0
  perl: 5.000
version: 1.01
