---
abstract: 'Add virtual columns to DBIx::Class schemata'
author:
  - 'Maroš Kollár'
build_requires:
  Class::C3: 0
  DBD::SQLite: 0
  ExtUtils::MakeMaker: 6.42
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-VirtualColumns
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/maros/DBIx-Class-VirtualColumns.git
version: 1.03
